package com.powersnj.registry;

import com.powersnj.PowersNJ;
import com.powersnj.block.SuitForgeBlock;
import com.powersnj.block.SuitStandBlock;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import net.minecraft.world.level.material.MapColor;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * Blocks. Block items are registered by {@link ModItems}.
 */
public final class ModBlocks {

    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, PowersNJ.MOD_ID);

    // Ores (generated by data/powersnj/worldgen + forge biome modifiers, gated by the server config)
    public static final RegistryObject<Block> VILTRUMITE_ORE = BLOCKS.register("viltrumite_ore",
            () -> new DropExperienceBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM)
                    .requiresCorrectToolForDrops().strength(4.5F, 9.0F), UniformInt.of(3, 7)));
    public static final RegistryObject<Block> DEEPSLATE_VILTRUMITE_ORE = BLOCKS.register("deepslate_viltrumite_ore",
            () -> new DropExperienceBlock(BlockBehaviour.Properties.of().mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM)
                    .requiresCorrectToolForDrops().strength(6.0F, 9.0F).sound(SoundType.DEEPSLATE), UniformInt.of(3, 7)));
    public static final RegistryObject<Block> SPEED_CRYSTAL_ORE = BLOCKS.register("speed_crystal_ore",
            () -> new DropExperienceBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM)
                    .requiresCorrectToolForDrops().strength(3.5F, 3.0F).lightLevel(state -> 4).sound(SoundType.AMETHYST), UniformInt.of(2, 5)));
    public static final RegistryObject<Block> DEEPSLATE_SPEED_CRYSTAL_ORE = BLOCKS.register("deepslate_speed_crystal_ore",
            () -> new DropExperienceBlock(BlockBehaviour.Properties.of().mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM)
                    .requiresCorrectToolForDrops().strength(5.0F, 3.0F).lightLevel(state -> 4).sound(SoundType.DEEPSLATE), UniformInt.of(2, 5)));

    public static final RegistryObject<Block> VILTRUMITE_BLOCK = BLOCKS.register("viltrumite_block",
            () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GRAY).requiresCorrectToolForDrops().strength(25.0F, 1200.0F).sound(SoundType.NETHERITE_BLOCK)));

    // Machines
    public static final RegistryObject<Block> SUIT_FORGE = BLOCKS.register("suit_forge",
            () -> new SuitForgeBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).requiresCorrectToolForDrops().strength(5.0F, 12.0F)
                    .sound(SoundType.NETHERITE_BLOCK).noOcclusion().lightLevel(state -> state.getValue(SuitForgeBlock.WORKING) ? 10 : 3)));
    public static final RegistryObject<Block> SUIT_STAND = BLOCKS.register("suit_stand",
            () -> new SuitStandBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(2.5F, 6.0F).sound(SoundType.METAL).noOcclusion()));

    private ModBlocks() {
    }
}
